services:

  # MongoDB service
  mongo:
    image: mongo:4 # Use a specific version tag or "latest" for the latest stable version
    container_name: mongodb-server # Lowercase and underscores (naming convention)
    volumes:
      - ./mongo-data:/data/db  # Persist data volume
      - ./mongo-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js # Mount init data (read-only)
    restart: always # Restart MongoDB on container failure
    networks:
      - mongo-compose-network

  # Mongo Express service (management UI)
  mongoexpress:
    image: mongo-express
    container_name: mongo-express  
    ports:
      - "8081:8081"  # Map container port 8081 to host port 8081
    environment: 
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017 # MongoDB connection string
    depends_on:
      - mongo  # Ensure Mongo service starts before Mongo Express
    restart: always
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
    